version: "2.4"
services:
  router:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "2626:8080"
    restart: on-failure
    links:
      - "site:site"
      - "redcycle-api:redcycle-api"
      - "redcycle-ui:redcycle-ui"
    volumes:
      - ./server:/usr/src/app/server
  site:
    build:
      context: ../drew-robert-site
      dockerfile: dev.Dockerfile
    ports:
      - "32768:3000"
    restart: on-failure
    volumes:
      - ../drew-robert-site/src:/usr/src/app/src
      - ../drew-robert-site/public:/usr/src/app/public
  redcycle-api:
    build:
      context: ../redcycle/redcycle-api
      dockerfile: dev.Dockerfile
    ports:
      - "2602:8000"
    restart: on-failure
    volumes:
      - ../redcycle/redcycle-api:/code
  redcycle-ui:
    build:
      context: ../redcycle/redcycle-ui
      dockerfile: dev.Dockerfile
    ports:
      - "2601:3000"
    volumes:
      - ../redcycle/redcycle-ui/src:/usr/src/app/src
      - ../redcycle/redcycle-ui/public:/usr/src/app/public
