version: "2.4"
services:
  router:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "32768:8080"
    restart: on-failure
  site:
    build:
      context: ../drew-robert-site
      dockerfile: prod.Dockerfile
    ports:
      - "2626:3000"

    restart: on-failure
    volumes:
      - ${PWD}:/app
      - /app/node_modules
