version: "2.4"
services:
  drew-robert-api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "2601:8080"
    restart: on-failure
    volumes:
      - ./server:/usr/src/app/server
