version: "2.4"
services:
  router:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "2626:8080"
    restart: on-failure
    links:
      - "site:site"
      - "redcycle-api:redcycle-api"
  site:
    build:
      context: ../drew-robert-site
      dockerfile: dev.Dockerfile
    ports:
      - "32768:3000"
    restart: on-failure
  redcycle-api:
    build:
      context: ../redcycle/redcycle-api
      dockerfile: prod.Dockerfile
    ports:
      - "2627:80"
    restart: on-failure
