version: "2.4"
services:
  router:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "2626:8080"
    restart: on-failure
  site:
    build:
      context: ../drew-robert-site
      dockerfile: dev.Dockerfile
    ports:
      - "32768:3000"
    restart: on-failure
