apiVersion: apps/v1
kind: Deployment
metadata:
  name: drew-robert-api-deployment
  namespace: drew-robert-namespace
  labels:
    app: drew-robert-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drew-robert-api
  template:
    metadata:
      labels:
        app: drew-robert-api
    spec:
      containers:
        - name: drew-robert-api
          image: drob1260/drew-robert-api:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: secret-files
              readOnly: true
              mountPath: "/usr/src/app/secret-files"
          env:
            - name: FLICKR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: drew-robert-api-secret
                  key: FLICKR_API_KEY
            - name: FLICKR_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: drew-robert-api-secret
                  key: FLICKR_API_SECRET
      volumes:
        - name: secret-files
          secret:
            secretName: drew-robert-api-secret
            items:
              - key: GoogleApiCredentials.json
                path: "GoogleApiCredentials.json"
                mode: 0400
