apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: drew-robert-api-ingress
  namespace: drew-robert-namespace
spec:
  rules:
  - host: www.drewrobert.com
    http:
      paths:
      - backend:
          service:
            name: drew-robert-api-service
            port:
              name: dr-api-port
        path: /api
        pathType: ImplementationSpecific
  - host: drewrobert.com
    http:
      paths:
      - backend:
          service:
            name: drew-robert-api-service
            port:
              name: dr-api-port
        path: /api
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - drewrobert.com
    - www.drewrobert.com
    secretName: drewrobert.com
