export type MmeForumOrder = {
  orderEntryNumber: number;
  mmeForumUsername: string;
  orderNumber: string;
  orderDate: string;
  estimatedBuildDate: string;
  actualBuildDate: string;
  estimatedDeliveryDate: string;
  actualDeliveryDate: string;
  vin: string;
  vinReceived: boolean;
  daysBetweenOrderAndBuild: number;
  daysBetweenOrderAndDelivery: number;
  daysBetweenBuildAndDelivery: number;
  location: string;
  locationNonUS: string;
  exteriorColor: string;
  modelYear: string;
  model: string;
  driveTrain: string;
  battery: string;
};
