
name: Pull Request Workflow

on: [pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout Repo
        uses: actions/checkout@v2
      - 
        name: built and test
        run: 
          - npm ci
          - npm run build
          - npm run test
